environment:

  matrix:

    - PYTHON: "C:\Miniconda-x64"

matrix:
  fast_finish: true

install:
  - set PATH=%CONDPATH%-x64\bin;%CONDAPATH%-x64\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q --name python%PYTHON_VERSION%-%PLATFORM% python=%PYTHON_VERSION% 
  - activate python%PYTHON_VERSION%-%PLATFORM%
  - conda install -q setuptools matplotlib nose pandas wheel scipy sphinx lockfile pip libpython
  - conda install -q -c msys2 m2w64-toolchain

build_script:
- cmd: |
    python -m pip install --upgrade pip
    python -m pip install --upgrade setuptools wheel twine numpy

    cd src
    python setup.py build

    copy ..\bin\*.* ..\wheel\dbr\
    cd build\lib.win-*\
    copy *.* ..\..\..\wheel\dbr\
    cd ..\..\..\wheel\

    python setup.py bdist_wheel

artifacts:
- path: wheel\dist\*.whl
  name: wheels